apiVersion: v1
kind: ConfigMap
metadata:
  name: link-tree-configmap
  namespace: link-tree
data:
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_APP_URL: "https://linktree.example.com"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/"
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/"

