apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-tree-deployment
  namespace: link-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-tree
  template:
    metadata:
      labels:
        app: link-tree
    spec:
      containers:
        - name: link-tree
          image: gopal161/link-tree-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            # ---- ConfigMap values ----
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                configMapKeyRef:
                  name: link-tree-configmap
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_URL

            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: link-tree-configmap
                  key: NEXT_PUBLIC_APP_URL

            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              valueFrom:
                configMapKeyRef:
                  name: link-tree-configmap
                  key: NEXT_PUBLIC_CLERK_SIGN_UP_URL

            - name: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: link-tree-configmap
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL

            - name: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: link-tree-configmap
                  key: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL

            # ---- Secret values ----
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: link-tree-secret
                  key: DATABASE_URL

            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: link-tree-secret
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: link-tree-secret
                  key: CLERK_SECRET_KEY

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 20
