apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: link-tree-ingress
  namespace: link-tree
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: "13.203.72.216.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: link-tree-service
            port:
              number: 80
